<?php

namespace Backend\SuperAdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstitucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitucionRepository extends EntityRepository
{
}
