parameters:
#    notificaciones.example.class: Frontend\NotificacionesBundle\Example

services:
#    notificaciones.example:
#        class: %notificaciones.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
