<?php

namespace Frontend\AjustesGeneralesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SedeRepository extends EntityRepository
{
}
