parameters:
#    observaciones.example.class: Frontend\ObservacionesBundle\Example

services:
#    observaciones.example:
#        class: %observaciones.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
