parameters:
#    estadisticas.example.class: Frontend\EstadisticasBundle\Example

services:
#    estadisticas.example:
#        class: %estadisticas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
