parameters:
#    docente.example.class: Frontend\DocenteBundle\Example

services:
#    docente.example:
#        class: %docente.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
