parameters:
#    aulavirtual.example.class: Frontend\AulavirtualBundle\Example

services:
#    aulavirtual.example:
#        class: %aulavirtual.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
